language: php
php:
- '5.6'
- '7.3'
# - nightly
services:
- mysql
script:
- mysql -e 'CREATE DATABASE gatherling DEFAULT CHARACTER SET latin1;'
- cp config.php.travisci config.php
- php admin/db-upgrade.php
- php util/insertcardset.php M10
- php util/updateDefaultFormats.php
- phpunit -v tests/
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
