apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: gcr.io/katelyn-gigante-gatherling/server
    context: .
    docker:
      dockerfile: Dockerfile
  local:
    push: false
deploy:
  kubectl:
    manifests:
    - deployment.yaml
